[versions]
adventure = "5.2.0" # https://mvnrepository.com/artifact/net.kyori/adventure-api
commandapi = "12.0.0" # https://central.sonatype.com/artifact/dev.jorel/commandapi-paper-shade
jspecify = "1.0.1" # https://mvnrepository.com/artifact/org.jspecify/jspecify
junit = "6.1.3" # https://mvnrepository.com/artifact/org.junit/junit-bom
mockito = "5.23.0" # https://mvnrepository.com/artifact/org.mockito/mockito-bom
mockbukkit = "4.116.1" # https://central.sonatype.com/namespace/org.mockbukkit.mockbukkit
paper-api = "26.2.build.+" # https://repo.papermc.io/ui/packages?name=io.papermc.paper%3Apaper-api&type=packages | Don't forget to update the api version paper-plugin.yml | You can see api-version pattern here https://docs.papermc.io/paper/dev/getting-started/paper-plugins/
shadow = "9.6.1" # https://plugins.gradle.org/plugin/com.gradleup.shadow

[libraries]
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
commandapi-shade = { module = "dev.jorel:commandapi-paper-shade", version.ref = "commandapi" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mockito-bom = { module = "org.mockito:mockito-bom", version.ref = "mockito" }
mockito = { module = "org.mockito:mockito-core" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter" }
mockbukkit = { module = "org.mockbukkit.mockbukkit:mockbukkit-v26.2", version.ref = "mockbukkit" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
